### PR TITLE
dynamic way of detecting brew

### PR DESCRIPTION
**Pull request by HaniAlshikh**
it solves the problem mentioned this [issue](https://github.com/munkireport/homebrew/issues/1), where brew could be installed somewhere else and not only in /usr/local/bin/brew.

### CODE REVIEW

**Comment by tuxudo** [comment]
This appears to break if there is no user logged in. It also doesn't check for brew in /usr/local/

**Comment by HaniAlshikh** [comment]
Oh yes, i forgot about the case where no user is logged in. I'm thinking if there is no user fall back to /usr/local/bin/brew what do you think?

and could you be a bit more descriptive about it not checking /usr/local? cuz i tested it with multiple machines having brew in /usr/local and i had no problems with it.

command -v brew requires brew to be in the user PATH, but if not i should have had a back plan :).

Ok, i will try something out.

**Comment by tuxudo** [comment]
You'll have to collect the brew data for each user and in the /usr/local/. All of that data must be merged into one file and sent to the server for processing. The model/processor will have to be changed to accept the new merged format while keeping compatibility with the older single format. A new column will need to be added to the database containing where the binary lives and it'll need to be added to the listing and client tab.

Don't rely on PATH variables in MunkiReport scripts. Always call out the exact path to the binary.

**Comment by HaniAlshikh** [comment]
I see your point and i would love to do this but for now i wasn't planning a major update like this. This will take me a bit to do as i need to do my homework on the whole module structure and how they really work and so on.

for now all that i wanted to do is to get the homebrew modules to gather data from brew installation, that happens to be in another folder, which can be any folder, that is why i'm relying on the PATH variables to determine where the brew instance could be. Therefore i was testing the following solution:

```bash
CURRENTUSER=$(/usr/bin/python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

if [[ $CURRENTUSER != "" ]]; then
    brew=$(sudo -i -u $CURRENTUSER command -v brew)

    if [[ $? = 1 ]]; then
        brew="/usr/local/bin/brew"
    fi
else
    brew="/usr/local/bin/brew"
fi
```

but if you find it to be more case-specific and not really a general need i could try to make a copy module from yours and use it in my firm, tell i get enough time to try doing what you suggested :).

**Comment by tuxudo** [comment]
Looking better. The script only captures the current logged in user or the /usr/local brew installation. It doesn't capture all users and /user/local

**Comment by HaniAlshikh** [comment]
exactly that's what I'm trying to archive for now.

**Pull request merged**
